[workspace]
members = [
    "backend",
    "lib",
    "frontend-wasm",
    "ai-runner-rs",
    #    "python",
]
resolver = "3"

[profile.release]
debug = true

[profile.release.package.frontend-wasm]
opt-level = "s"
